### PR TITLE
Included error messages

### PR DESCRIPTION
**Pull request by Eknir**
- What about Other types (Uri, ByteArray, others?)? 
- Is it possible to print and error message if not Int (exclusive), instead of printing error messages in an inclusive way showed here?

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
This is definitely a good idea. What do you think about the paradigm of passing in two channels like
```
new return, error in {
  abs!(5, *return, *error)
}
```
Then you get something back on exactly one of the error and return channels. Kind of like javascript promises.

**Comment by Eknir** [comment]
What about this @JoshOrndorff ?

**Comment by JoshOrndorff** [comment]
Looking pretty good. I'm just not seeing why `inputChecker` was necessary. What if we 
```
contarct abs(@input, return error) = {
  match input {
    inp /\ Int => whatever
    _ => whatever
  }
}
```

**Comment by JoshOrndorff** [comment]
btw, I'm having fun exploring this and learning with you. If revising becomes a pain I'll happily merge.

**Comment by Eknir** [comment]
I like it too. If you are patient, I'll definitely propose a revision.

**Pull request merged**
